# Generated by Django 4.2.23 on 2026-07-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Do not enter anything here', null=True)),
            ],
            options={
                'verbose_name': 'Organization ',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Do not enter anything here', null=True)),
            ],
            options={
                'verbose_name': 'Employee Rank',
                'verbose_name_plural': 'Employee Rank',
            },
        ),
        migrations.CreateModel(
            name='StaffRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Do not enter anything here', null=True)),
            ],
            options={
                'verbose_name': 'Employee Rank',
                'verbose_name_plural': 'Employee Rank',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Do not enter anything here', null=True)),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Role',
            },
        ),
        migrations.CreateModel(
            name='StaffDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.staffrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.staff')),
            ],
        ),
    ]
