# Generated by Django 4.2.23 on 2026-07-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffdeployment',
            options={'ordering': ['-is_current', '-start_date']},
        ),
        migrations.AlterField(
            model_name='staffdeployment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='organization.company'),
        ),
        migrations.AlterField(
            model_name='staffdeployment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='staffdeployment',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='organization.staffrole'),
        ),
        migrations.AlterField(
            model_name='staffdeployment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='employees.staff'),
        ),
    ]
