# Generated by Django 4.2.23 on 2026-07-04 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employees.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardReissueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_card_number', models.CharField(max_length=30)),
                ('new_card_number', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('Reissued', 'Reissued'), ('Revoked', 'Revoked')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ID Card Reissue Log',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_no', models.CharField(blank=True, db_index=True, help_text='Automatically generated employee number', max_length=20, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('state_of_origin', models.CharField(choices=[('Select', 'Select'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT Abuja', 'FCT Abuja'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], default='Select', max_length=30)),
                ('nationality', models.CharField(default='Nigeria', max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Casual', 'Casual'), ('Intern', 'Intern'), ('NYSC', 'NYSC'), ('Probation', 'Probation')], default='Permanent', max_length=20)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Retired', 'Retired')], default='Active', max_length=20)),
                ('date_employed', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=20)),
                ('phone_home', models.CharField(blank=True, max_length=20)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_phone', models.CharField(blank=True, max_length=20)),
                ('guarantor_email', models.EmailField(blank=True, max_length=254)),
                ('guarantor_address', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
        migrations.CreateModel(
            name='StaffIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Passport photograph. Falls back to initials if omitted.', null=True, upload_to=employees.models.staff_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to=employees.models.staff_qr_upload_path)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Revoked', 'Revoked'), ('Lost / Reissued', 'Lost / Reissued')], default='Active', max_length=20)),
                ('is_printed', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(help_text='Each staff member has exactly one current ID card.', on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='employees.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff ID Card',
                'verbose_name_plural': 'Staff ID Cards',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checked_out', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.staff')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
