# Generated by Django 4.2.23 on 2026-07-01 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.staffrank'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['employee_no'], name='employees_s_employe_dc9242_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['employment_status'], name='employees_s_employm_dd141a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['date_employed'], name='employees_s_date_em_ef3b9e_idx'),
        ),
    ]
