# Generated by Django 4.2.23 on 2026-06-30 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeRank',
            new_name='StaffRank',
        ),
        migrations.RenameModel(
            old_name='EmployeeRole',
            new_name='StaffRole',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('select_gender', 'select_gender')], default='select_gender', max_length=20)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('state_of_origin', models.CharField(choices=[('Select', 'Select'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa_ibom', 'Akwa_Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross_river', 'Cross_river'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Fct_abuja', 'Fct_abuja'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], default='Select', max_length=15)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('select', 'select')], default='select', max_length=15)),
                ('date_employed', models.DateField(default='1998-01-01')),
                ('phone_home', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=150, null=True)),
                ('qualification', models.CharField(default='OND', max_length=150)),
                ('year', models.DateField(default='1998-01-01')),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_phone', models.CharField(blank=True, max_length=15)),
                ('guarantor_address', models.CharField(blank=True, max_length=150)),
                ('guarantor_email', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('dept_assigned', models.ManyToManyField(blank=True, related_name='employees', to='employees.department')),
                ('organization_assigned', models.ManyToManyField(related_name='employees', to='employees.organization')),
                ('role_assigned', models.ManyToManyField(blank=True, related_name='employees', to='employees.staffrole')),
                ('staff_rank', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_dept', to='employees.staffrank')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Details',
                'verbose_name_plural': 'Staff Details',
                'ordering': ['last_name'],
            },
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.staff'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
