# Generated by Django 4.2.23 on 2026-07-04 06:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employees.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Passport photograph. Falls back to initials if omitted.', null=True, upload_to=employees.models.staff_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to=employees.models.staff_qr_upload_path)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Revoked', 'Revoked'), ('Lost / Reissued', 'Lost / Reissued')], default='Active', max_length=20)),
                ('is_printed', models.BooleanField(default=False)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(help_text='Each staff member has exactly one current ID card.', on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='employees.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff ID Card',
                'verbose_name_plural': 'Staff ID Cards',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='IDCardReissueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_card_number', models.CharField(max_length=30)),
                ('new_card_number', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('Reissued', 'Reissued'), ('Revoked', 'Revoked')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reissue_logs', to='employees.staffidcard')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Card Reissue Log',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffidcard',
            index=models.Index(fields=['card_number'], name='employees_s_card_nu_7b6e54_idx'),
        ),
        migrations.AddIndex(
            model_name='staffidcard',
            index=models.Index(fields=['status'], name='employees_s_status_5e5788_idx'),
        ),
    ]
