# Generated by Django 4.2.23 on 2026-07-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='custodian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='pension_pin',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
