"""
organization/models.py  (additions)
───────────────────────────────────────────────────────────────────────────
CorporateIdentity  — stores company branding used on ID cards, payslips,
                     and all official printed/PDF output.

BranchIdentity     — optional per-branch identity override.
                     If a branch has a BranchIdentity record, that
                     company's branding is used instead of the default
                     for any document belonging to staff deployed to
                     that branch.

Rationale
─────────
A manpower outsourcing company may operate multiple branches that carry
different trading names, logos, or contact details (e.g. a Lagos branch
and an Abuja branch with separate letterheads). BranchIdentity lets you
map each branch to the correct branding without duplicating logic in
every view or template.

Identity resolution order (enforced by the context processor):
  1. Branch-specific identity (BranchIdentity → CorporateIdentity)
  2. Default identity        (CorporateIdentity.is_default = True)
  3. Fallback                (first CorporateIdentity in the database)

Placement in your project
─────────────────────────
Append these models to your existing organization/models.py.
Do NOT copy the imports — merge them with what you already have.

Migration
─────────
  python manage.py makemigrations organization
  python manage.py migrate
───────────────────────────────────────────────────────────────────────────
"""

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify


# ─────────────────────────────────────────────────────────────────────────────
# Corporate Identity
# ─────────────────────────────────────────────────────────────────────────────

class CorporateIdentity(models.Model):
    """
    Company branding record.

    Printed on:
      • Staff ID cards
      • Salary payslips
      • Loan letters
      • Appointment / promotion letters
      • Any PDF generated by the system

    You can create up to 10 identities (e.g. one per major branch or
    subsidiary). Exactly one must be marked is_default=True — this is
    the fallback used whenever no branch-specific identity is found.
    """

    # ── Identity label ─────────────────────────────────────────────────────
    name = models.CharField(
        max_length=100,
        help_text="Official company / subsidiary name printed on documents.",
    )
    identity_label = models.CharField(
        max_length=60,
        blank=True,
        help_text=(
            "Short internal label to distinguish identities. "
            "e.g. 'Head Office', 'Lagos Branch', 'Abuja Subsidiary'."
        ),
    )
    is_default = models.BooleanField(
        default=False,
        help_text=(
            "The default identity is used when no branch-specific "
            "identity is mapped. Exactly one record should be default."
        ),
    )

    # ── Contact & address ──────────────────────────────────────────────────
    address = models.CharField(
        max_length=200,
        help_text="Street address line 1 (printed on documents).",
    )
    address_line_2 = models.CharField(
        max_length=200,
        blank=True,
        help_text="City, State, Country — printed below address line 1.",
    )
    phone = models.CharField(
        max_length=20,
        help_text="Primary phone number.",
    )
    phone_2 = models.CharField(
        max_length=20,
        blank=True,
        help_text="Secondary / WhatsApp number (optional).",
    )
    email = models.EmailField(
        blank=True,
        help_text="Official email address printed on documents.",
    )
    website = models.URLField(
        blank=True,
        help_text="Company website URL (optional).",
    )
    rc_number = models.CharField(
        max_length=30,
        blank=True,
        verbose_name="RC / TIN Number",
        help_text="CAC Registration or Tax Identification Number (optional).",
    )

    # ── Branding assets ────────────────────────────────────────────────────
    logo = models.ImageField(
        upload_to="corporate/logos/",
        blank=True,
        null=True,
        help_text=(
            "Company logo. Recommended: transparent PNG, max 300×300 px. "
            "Displayed on ID cards, payslips, and letterheads."
        ),
    )
    signature = models.ImageField(
        upload_to="corporate/signatures/",
        blank=True,
        null=True,
        help_text=(
            "Authorised signatory image. Recommended: transparent PNG. "
            "Printed at the bottom of payslips and official letters."
        ),
    )
    signatory_name = models.CharField(
        max_length=150,
        blank=True,
        help_text="Full name of the person whose signature appears on documents.",
    )
    signatory_title = models.CharField(
        max_length=100,
        blank=True,
        help_text="Title of the signatory, e.g. 'Managing Director'.",
    )

    # ── Colours for printed/digital documents ─────────────────────────────
    primary_colour = models.CharField(
        max_length=7,
        default="#0B1D3A",
        help_text="Primary brand colour (hex, e.g. #0B1D3A). Used on ID cards.",
    )
    accent_colour = models.CharField(
        max_length=7,
        default="#C9A84C",
        help_text="Accent / secondary colour (hex, e.g. #C9A84C).",
    )

    # ── Meta ───────────────────────────────────────────────────────────────
    slug = models.SlugField(
        max_length=110,
        unique=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Corporate Identity"
        verbose_name_plural = "Corporate Identities"
        ordering = ["-is_default", "name"]

    # ── String representation ──────────────────────────────────────────────
    def __str__(self) -> str:
        label = f" ({self.identity_label})" if self.identity_label else ""
        return f"{self.name}{label}"

    # ── Model-level validation ─────────────────────────────────────────────
    def clean(self):
        if not self.pk and CorporateIdentity.objects.exists():
            raise ValidationError(
                "Only one Corporate Identity can exist. "
                "Please edit the existing record instead of creating another."
            )

    # ── Save override ──────────────────────────────────────────────────────
    def save(self, *args, **kwargs) -> None:
        # Auto-generate slug from company name
        if not self.slug:
            base = slugify(self.name)
            slug = base
            n = 1
            while CorporateIdentity.objects.filter(slug=slug).exclude(pk=self.pk).exists():
                slug = f"{base}-{n}"
                n += 1
            self.slug = slug

        # Ensure at most one default; demote all others atomically
        if self.is_default:
            CorporateIdentity.objects.filter(
                is_default=True
            ).exclude(pk=self.pk).update(is_default=False)

        self.full_clean()  # run clean()
        super().save(*args, **kwargs)

    # ── Convenience properties ─────────────────────────────────────────────
    @property
    def full_address(self) -> str:
        """Return a single-line full address for templates."""
        parts = [self.address]
        if self.address_line_2:
            parts.append(self.address_line_2)
        return ", ".join(parts)

    @property
    def has_logo(self) -> bool:
        return bool(self.logo)

    @property
    def has_signature(self) -> bool:
        return bool(self.signature)

    @classmethod
    def get_default(cls) -> "CorporateIdentity | None":
        """
        Returns the default identity, falling back to the first record.
        Safe to call even if no records exist — returns None.
        """
        return (
            cls.objects.filter(is_default=True).first()
            or cls.objects.first()
        )

