# Generated by Django 4.2.23 on 2026-07-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_staffidcard_idcardreissuelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('promotion_order', models.IntegerField(blank=True, help_text='Order of Branch )', null=True, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('branch_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager', to='employees.staff')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='CorporateIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identity_label', models.CharField(blank=True, help_text='e.g. Primary, Secondary, or Main', max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback identity if no specific class identity is set.')),
                ('address', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('phone1', models.CharField(max_length=11)),
                ('phone2', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(default='school_logo.jpg', help_text='must not exceed 180px by 180px in size', upload_to='official_pics')),
                ('signature', models.ImageField(blank=True, help_text='must not exceed 180px by 180px in size', null=True, upload_to='official_pics')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corporate Identity Setting',
                'verbose_name_plural': 'Corporate Identity Settings',
            },
        ),
        migrations.CreateModel(
            name='BranchIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_mapping', to='dashboard.branch')),
                ('corporate_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.corporateidentity')),
            ],
            options={
                'verbose_name': 'Branch-Identity Mapping',
                'verbose_name_plural': 'Branch-Identity Mappings',
            },
        ),
    ]
