# Generated by Django 4.2.23 on 2026-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official company / subsidiary name printed on documents.', max_length=100)),
                ('identity_label', models.CharField(blank=True, help_text="Short internal label to distinguish identities. e.g. 'Head Office', 'Lagos Branch', 'Abuja Subsidiary'.", max_length=60)),
                ('is_default', models.BooleanField(default=False, help_text='The default identity is used when no branch-specific identity is mapped. Exactly one record should be default.')),
                ('address', models.CharField(help_text='Street address line 1 (printed on documents).', max_length=200)),
                ('address_line_2', models.CharField(blank=True, help_text='City, State, Country — printed below address line 1.', max_length=200)),
                ('phone', models.CharField(help_text='Primary phone number.', max_length=20)),
                ('phone_2', models.CharField(blank=True, help_text='Secondary / WhatsApp number (optional).', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Official email address printed on documents.', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website URL (optional).')),
                ('rc_number', models.CharField(blank=True, help_text='CAC Registration or Tax Identification Number (optional).', max_length=30, verbose_name='RC / TIN Number')),
                ('logo', models.ImageField(blank=True, help_text='Company logo. Recommended: transparent PNG, max 300×300 px. Displayed on ID cards, payslips, and letterheads.', null=True, upload_to='corporate/logos/')),
                ('signature', models.ImageField(blank=True, help_text='Authorised signatory image. Recommended: transparent PNG. Printed at the bottom of payslips and official letters.', null=True, upload_to='corporate/signatures/')),
                ('signatory_name', models.CharField(blank=True, help_text='Full name of the person whose signature appears on documents.', max_length=150)),
                ('signatory_title', models.CharField(blank=True, help_text="Title of the signatory, e.g. 'Managing Director'.", max_length=100)),
                ('primary_colour', models.CharField(default='#0B1D3A', help_text='Primary brand colour (hex, e.g. #0B1D3A). Used on ID cards.', max_length=7)),
                ('accent_colour', models.CharField(default='#C9A84C', help_text='Accent / secondary colour (hex, e.g. #C9A84C).', max_length=7)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate Identity',
                'verbose_name_plural': 'Corporate Identities',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
