# Generated by Django 4.2.23 on 2026-07-06 06:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advance Repayment',
                'verbose_name_plural': 'Advance Repayments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Active', 'Being Repaid'), ('Settled', 'Fully Repaid'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('Recurring', 'Recurring (every payroll)'), ('One-Time', 'One-Time')], default='Recurring', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Staff Allowance',
                'verbose_name_plural': 'Staff Allowances',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, help_text='CBN bank sort/routing code, if known.', max_length=10)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=20)),
                ('bvn', models.CharField(blank=True, help_text='Bank Verification Number.', max_length=11)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Staff Bank Account',
                'verbose_name_plural': 'Staff Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='StaffDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('Recurring', 'Recurring (every payroll)'), ('One-Time', 'One-Time')], default='Recurring', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for an open-ended recurring deduction.', null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_suspended', models.BooleanField(default=False, help_text='Temporarily skip without deleting the instruction.')),
            ],
            options={
                'verbose_name': 'Staff Deduction',
                'verbose_name_plural': 'Staff Deductions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'ordering': ['category', 'display_order', 'name'], 'verbose_name': 'Salary Component', 'verbose_name_plural': 'Salary Components'},
        ),
        migrations.RemoveIndex(
            model_name='salarycomponent',
            name='payroll_sal_compone_c97d5c_idx',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='calculated_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='payrolljournal',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='component_type',
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='nature',
            field=models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], default='Earning', editable=False, help_text='Snapshotted at creation — Earning or Deduction.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='nature',
            field=models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], default='Earning', help_text='Whether this component adds to or subtracts from pay.', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='apply_on_gross',
            field=models.BooleanField(default=False, help_text='If Percentage and no percentage_of is set, base the percentage on gross salary.'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='category',
            field=models.CharField(choices=[('Basic', 'Basic Salary'), ('Allowance', 'Allowance'), ('Bonus', 'Bonus'), ('Overtime', 'Overtime'), ('Reimbursement', 'Reimbursement'), ('Tax', 'Tax'), ('Pension', 'Pension'), ('NHF', 'National Housing Fund'), ('Loan', 'Loan Repayment'), ('Advance', 'Salary Advance'), ('Penalty', 'Penalty'), ('Deduction', 'Other Deduction'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='formula',
            field=models.CharField(blank=True, help_text="Only used when calculation method is Formula. Supports + - * / and parentheses, referencing other component codes already calculated for this staff member this payroll, e.g. 'BASIC * 0.08' or 'BASIC + HOUSING'. Evaluated by a restricted parser — never Python eval().", max_length=255),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='percentage_of',
            field=models.ForeignKey(blank=True, help_text='Component used as the base for percentage calculation. Leave blank to calculate as a percentage of Gross Salary so far (see apply_on_gross).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_components', to='payroll.salarycomponent'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['category'], name='payroll_sal_categor_4a2af0_idx'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['nature'], name='payroll_sal_nature_3c2ef1_idx'),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='applied_in_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_time_deductions_applied', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_deductions', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='employees.staff'),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffbankaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffbankaccount',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='employees.staff'),
        ),
        migrations.AddField(
            model_name='staffbankaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='applied_in_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_time_allowances_applied', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_allowances', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances', to='employees.staff'),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='employees.staff'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='applied_in_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_penalties', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='imposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_imposed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='employees.staff'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='target_period',
            field=models.ForeignKey(help_text='The payroll period this penalty should be deducted in.', on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='applied_in_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses_applied', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_bonuses', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='employees.staff'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='target_period',
            field=models.ForeignKey(help_text='The payroll period this bonus should be paid in.', on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancerepayment',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='payroll.salaryadvance'),
        ),
        migrations.AddField(
            model_name='advancerepayment',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_repayments', to='payroll.payroll'),
        ),
        migrations.AddIndex(
            model_name='staffdeduction',
            index=models.Index(fields=['staff', 'is_active'], name='payroll_sta_staff_i_87129e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdeduction',
            index=models.Index(fields=['start_date'], name='payroll_sta_start_d_3689f3_idx'),
        ),
        migrations.AddIndex(
            model_name='staffbankaccount',
            index=models.Index(fields=['account_number'], name='payroll_sta_account_235580_idx'),
        ),
        migrations.AddIndex(
            model_name='staffallowance',
            index=models.Index(fields=['staff', 'is_active'], name='payroll_sta_staff_i_5601aa_idx'),
        ),
        migrations.AddIndex(
            model_name='staffallowance',
            index=models.Index(fields=['start_date'], name='payroll_sta_start_d_95dba4_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['staff', 'status'], name='payroll_sal_staff_i_1fd970_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['staff', 'status'], name='payroll_pen_staff_i_662ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['target_period'], name='payroll_pen_target__a94bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['staff', 'status'], name='payroll_bon_staff_i_f2e86f_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['target_period'], name='payroll_bon_target__1db17c_idx'),
        ),
        migrations.AddConstraint(
            model_name='advancerepayment',
            constraint=models.UniqueConstraint(fields=('advance', 'payroll'), name='unique_advance_repayment_per_payroll'),
        ),
    ]
